logLevel: error
logFormat: json
clusterName: my-super-local-cluster
route:
  routes:
    - match:
        - receiver: "dump"
receivers:
  - name: "slack"
        slack:
          token: ${SLACK_TOKEN}
          channel: "#random"
          message: "{{ .Message }}"
          fields:
            namespace: "{{ .Namespace }}"
            reason: "{{ .Reason }}"
            object: "{{ .Namespace }}"