apiVersion: v1
kind: ConfigMap
metadata:
  name: event-exporter-cfg
  namespace: monitoring
data:
  config.yaml: |
    logLevel: warn
    logFormat: json
    metricsNamePrefix: event_exporter_
    route:
      routes:
        - match:
            - receiver: "dump"
    receivers:
      - name: "slack"
        slack:
          token: ${SLACK_TOKEN}
          channel: "@{{ .InvolvedObject.Labels.owner }}"
          message: "{{ .Message }}"
          fields:
            namespace: "{{ .Namespace }}"
            reason: "{{ .Reason }}"
            object: "{{ .Namespace }}"